name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  your-image-name: meu-site
  your-aws-account-id: ${{ secrets.SECRET_ID }}
  your-region: ${{ secrets.SECRET_REGION }}
  your-ecs-cluster-name: ${{ secrets.CLUSTER }}
  your-ecs-service-name: ${{ secrets.SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        id: login-ecr
        uses: actions/checkout@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.SECRET_REGION }} # Corrigi para usar SECRETS_REGION ao invés de SECRET_REGION

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t $your-image-name .

      - name: Tag Docker image
        run: docker tag $your-image-name:latest $your-aws-account-id.dkr.ecr.$your-region.amazonaws.com/$your-image-name:latest
      
      - name: Create ECR Repository
        run: aws ecr create-repository --repository-name meu-site --region $your-region # Corrigi para usar $your-region ao invés de ${{ secrets.SECRET_REGION }}

      - name: Push Docker image to ECR
        run: docker push $your-aws-account-id.dkr.ecr.$your-region.amazonaws.com/$your-image-name:latest
