name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      your_image_name: "meu-site"
      your_aws_account_id: ${{ secrets.SECRET_ID }}
      your_region: ${{ secrets.SECRET_REGION }}
      your_ecs_cluster_name: ${{ secrets.CLUSTER }}
      your_ecs_service_name: ${{ secrets.SERVICE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $your_image_name .

      - name: Tag Docker image
        run: |
          docker tag $your_image_name:latest $your_aws_account_id.dkr.ecr.$your_region.amazonaws.com/$your_image_name:latest

      - name: Push Docker image to ECR
        run: |
          docker push $your_aws_account_id.dkr.ecr.$your_region.amazonaws.com/$your_image_name:latest

      - name: Update ECS Service
        uses: aws-actions/amazon-ecs-deploy-task@v2
        with:
          cluster: $your_ecs_cluster_name
          service: $your_ecs_service_name
          image: $your_aws_account_id.dkr.ecr.$your_region.amazonaws.com/$your_image_name:latest
          credentials: |
            ${{ secrets.AWS_ACCESS_KEY_ID }},
            ${{ secrets.SECRET_ACCESS_KEY }}
